// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9PXcoFnS2PUIvq4D7GaoolaN6l8O0jnM',
    appId: '1:1033194167439:web:c543ae1a3df33e7288e4fa',
    messagingSenderId: '1033194167439',
    projectId: 'dwellite-433d3',
    authDomain: 'dwellite-433d3.firebaseapp.com',
    storageBucket: 'dwellite-433d3.appspot.com',
    measurementId: 'G-9V1ZYT481F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1Yg9iKOwwHLFsBNE-BEeDZNtUBy1trk',
    appId: '1:1033194167439:android:cfba9418bca5987d88e4fa',
    messagingSenderId: '1033194167439',
    projectId: 'dwellite-433d3',
    storageBucket: 'dwellite-433d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgXX-37W8soSKue97VNGkBX0P2Dkh1NT8',
    appId: '1:1033194167439:ios:22ec136c488ecc3588e4fa',
    messagingSenderId: '1033194167439',
    projectId: 'dwellite-433d3',
    storageBucket: 'dwellite-433d3.appspot.com',
    iosBundleId: 'com.ozaidwellite.dwellite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgXX-37W8soSKue97VNGkBX0P2Dkh1NT8',
    appId: '1:1033194167439:ios:aa575de45578de0d88e4fa',
    messagingSenderId: '1033194167439',
    projectId: 'dwellite-433d3',
    storageBucket: 'dwellite-433d3.appspot.com',
    iosBundleId: 'com.solivar.dwellite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9PXcoFnS2PUIvq4D7GaoolaN6l8O0jnM',
    appId: '1:1033194167439:web:e3e2995daea04f7a88e4fa',
    messagingSenderId: '1033194167439',
    projectId: 'dwellite-433d3',
    authDomain: 'dwellite-433d3.firebaseapp.com',
    storageBucket: 'dwellite-433d3.appspot.com',
    measurementId: 'G-KJQ2SRJCS9',
  );
}
